name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.0.302
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      env: 
          API_KEY:  ${{ secrets.RB_API_KEY }}
      run: dotnet test --configuration Release
